2019-11-14 00:03:36,291 DEBUG   MainThread:5604 [wandb_config.py:_load_defaults():110] no defaults not found in config-defaults.yaml
2019-11-14 00:03:36,296 DEBUG   MainThread:5604 [cmd.py:execute():724] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/itrushkin/Documents/digit-recognizer, universal_newlines=False, shell=None, istream=<valid stream>)
2019-11-14 00:03:36,300 DEBUG   MainThread:5604 [cmd.py:execute():724] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/itrushkin/Documents/digit-recognizer, universal_newlines=False, shell=None, istream=None)
2019-11-14 00:03:36,302 DEBUG   MainThread:5604 [cmd.py:execute():724] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/itrushkin/Documents/digit-recognizer, universal_newlines=False, shell=None, istream=None)
2019-11-14 00:03:36,308 DEBUG   MainThread:5604 [run_manager.py:__init__():535] Initialized sync for digit-recognizer/9qzc9lrk
2019-11-14 00:03:36,311 INFO    MainThread:5604 [run_manager.py:wrap_existing_process():1131] wrapping existing process 5589
2019-11-14 00:03:36,311 WARNING MainThread:5604 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2019-11-14 00:03:36,314 DEBUG   MainThread:5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2019-11-14 00:03:36,511 DEBUG   MainThread:5604 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 37669
2019-11-14 00:03:36,552 INFO    MainThread:5604 [run_manager.py:init_run():916] system metrics and metadata threads started
2019-11-14 00:03:36,552 INFO    MainThread:5604 [run_manager.py:init_run():950] upserting run before process can begin, waiting at most 10 seconds
2019-11-14 00:03:36,561 DEBUG   Thread-14 :5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-14 00:03:36,939 DEBUG   Thread-14 :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 574
2019-11-14 00:03:36,949 INFO    Thread-14 :5604 [run_manager.py:_upsert_run():1035] saving patches
2019-11-14 00:03:36,950 DEBUG   Thread-14 :5604 [cmd.py:execute():724] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/itrushkin/Documents/digit-recognizer, universal_newlines=False, shell=None, istream=None)
2019-11-14 00:03:36,953 DEBUG   Thread-14 :5604 [cmd.py:execute():724] Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/home/itrushkin/Documents/digit-recognizer, universal_newlines=False, shell=None, istream=None)
2019-11-14 00:03:36,956 DEBUG   Thread-14 :5604 [cmd.py:execute():724] Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=/home/itrushkin/Documents/digit-recognizer, universal_newlines=False, shell=None, istream=None)
2019-11-14 00:03:36,962 DEBUG   Thread-14 :5604 [cmd.py:execute():724] Popen(['git', 'version'], cwd=/home/itrushkin/Documents/digit-recognizer, universal_newlines=False, shell=None, istream=None)
2019-11-14 00:03:36,970 DEBUG   Thread-14 :5604 [cmd.py:execute():724] Popen(['git', 'merge-base', 'HEAD', '4115426bb991efeae53858954449c83817cc731b'], cwd=/home/itrushkin/Documents/digit-recognizer, universal_newlines=False, shell=None, istream=None)
2019-11-14 00:03:36,973 INFO    Thread-14 :5604 [run_manager.py:_upsert_run():1039] saving pip packages
2019-11-14 00:03:36,974 INFO    Thread-14 :5604 [run_manager.py:_upsert_run():1041] initializing streaming files api
2019-11-14 00:03:36,974 INFO    Thread-14 :5604 [run_manager.py:_upsert_run():1048] unblocking file change observer, beginning sync with W&B servers
2019-11-14 00:03:36,975 INFO    MainThread:5604 [run_manager.py:wrap_existing_process():1148] informing user process we are ready to proceed
2019-11-14 00:03:36,977 INFO    MainThread:5604 [run_manager.py:_sync_etc():1255] entering loop for messages from user process
2019-11-14 00:03:36,978 DEBUG   Thread-15 :5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-14 00:03:37,218 DEBUG   Thread-15 :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 46
2019-11-14 00:03:37,296 INFO    Thread-3  :5604 [run_manager.py:_on_file_modified():682] file/dir modified: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/config.yaml
2019-11-14 00:03:37,302 DEBUG   Thread-3  :5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-14 00:03:37,579 DEBUG   Thread-3  :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 622
2019-11-14 00:03:37,582 INFO    Thread-3  :5604 [run_manager.py:_on_file_created():671] file/dir created: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/output.log
2019-11-14 00:03:37,582 INFO    Thread-3  :5604 [run_manager.py:_on_file_created():671] file/dir created: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/requirements.txt
2019-11-14 00:03:37,582 INFO    Thread-3  :5604 [run_manager.py:_on_file_created():671] file/dir created: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/diff.patch
2019-11-14 00:03:37,582 INFO    Thread-3  :5604 [run_manager.py:_on_file_created():671] file/dir created: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/wandb-metadata.json
2019-11-14 00:03:38,295 INFO    Thread-3  :5604 [run_manager.py:_on_file_created():671] file/dir created: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/wandb-summary.json
2019-11-14 00:03:39,296 INFO    Thread-3  :5604 [run_manager.py:_on_file_modified():682] file/dir modified: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/output.log
2019-11-14 00:03:39,297 INFO    Thread-3  :5604 [run_manager.py:_on_file_modified():682] file/dir modified: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/wandb-summary.json
2019-11-14 00:03:39,299 DEBUG   Thread-7  :5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-14 00:03:39,304 DEBUG   Thread-16 :5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-14 00:03:39,553 DEBUG   Thread-16 :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 804
2019-11-14 00:03:39,558 DEBUG   Thread-16 :5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2019-11-14 00:03:39,982 DEBUG   Thread-16 :5604 [connectionpool.py:_make_request():437] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/ilya-trushkin/digit-recognizer/9qzc9lrk/___batch_archive_1.tgz?Expires=1573679079&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=LZJQsJiUK0pnwVQwQ5GRb6oejMe6MPTspyFuNuLrqXY%2FD8fb7babXxZLYlLHh3IYcCJShDTHvvIqeP%2BO9s7US7WglzkxoCQe%2BnOSOc%2BhkHBO9%2FxPNf9k6DGOeE7HVBt0x75PkEHIiNOZTn8qfxRYd9X8z0LjbmyBzLYoY2xzhsaY1tZvKLeimpVI7BbOdmLrcgokg443n7tPql4PVAWp6yGVz%2FxXy9GcJVvB20d9WxYQBX%2BQod2Dac7JmfsxCmGmV370DxzZ%2B1ykENgpSfRRnL08K20%2B0S1DnUMXbgi7LHc%2B67CyZtG%2Bvi4i1rHnVhnfcvGxYSPfJH9lzKM3Aeuyzg%3D%3D HTTP/1.1" 200 0
2019-11-14 00:03:39,983 DEBUG   Thread-7  :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/ilya-trushkin/digit-recognizer/9qzc9lrk/file_stream HTTP/1.1" 200 311
2019-11-14 00:03:52,223 DEBUG   Thread-15 :5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-14 00:03:52,301 INFO    Thread-3  :5604 [run_manager.py:_on_file_modified():682] file/dir modified: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/output.log
2019-11-14 00:03:52,377 DEBUG   Thread-7  :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/ilya-trushkin/digit-recognizer/9qzc9lrk/file_stream HTTP/1.1" 200 311
2019-11-14 00:03:52,468 DEBUG   Thread-15 :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 46
2019-11-14 00:03:53,094 INFO    MainThread:5604 [run_manager.py:_sync_etc():1311] process received interrupt signal, shutting down
2019-11-14 00:03:53,094 INFO    MainThread:5604 [run_manager.py:_sync_etc():1364] closing log streams and sending exitcode to W&B
2019-11-14 00:03:53,095 INFO    MainThread:5604 [run_manager.py:shutdown():1055] shutting down system stats and metadata service
2019-11-14 00:03:53,302 INFO    Thread-3  :5604 [run_manager.py:_on_file_modified():682] file/dir modified: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/wandb-metadata.json
2019-11-14 00:03:53,302 INFO    Thread-3  :5604 [run_manager.py:_on_file_created():671] file/dir created: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/wandb-events.jsonl
2019-11-14 00:03:53,569 INFO    MainThread:5604 [run_manager.py:shutdown():1067] stopping streaming files and file change observer
2019-11-14 00:03:54,302 INFO    Thread-3  :5604 [run_manager.py:_on_file_modified():682] file/dir modified: /home/itrushkin/Documents/digit-recognizer/wandb/run-20191113_210335-9qzc9lrk/wandb-metadata.json
2019-11-14 00:03:54,311 DEBUG   MainThread:5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-14 00:03:54,623 DEBUG   MainThread:5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 622
2019-11-14 00:03:55,194 DEBUG   Thread-7  :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/ilya-trushkin/digit-recognizer/9qzc9lrk/file_stream HTTP/1.1" 200 311
2019-11-14 00:03:55,315 DEBUG   Thread-19 :5604 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-14 00:03:55,504 DEBUG   Thread-7  :5604 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/ilya-trushkin/digit-recognizer/9qzc9lrk/file_stream HTTP/1.1" 200 310
2019-11-14 00:03:55,505 INFO    MainThread:5604 [run_manager.py:_sync_etc():1376] process only ran for 19 seconds, not syncing files
2019-11-14 00:03:55,505 INFO    MainThread:5604 [9qzc9lrk:run_manager.py:_sync_etc():1376] process only ran for 19 seconds, not syncing files
